import os
import json
import glob
from langchain_google_genai import ChatGoogleGenerativeAI
# FIXED: Using the modern, production-grade LangChain Core import path
from langchain_core.prompts import PromptTemplate
from dotenv import load_dotenv

# Load security environment tokens
load_dotenv()


class SecurityIncidentAgent:
    def __init__(self):
        print("[INFO] Initializing LangChain Security Intelligence Agent...")
        # Get the Gemini API key from the environment variables
        api_key = os.getenv("GEMINI_API_KEY")

        # Configure LangChain to use the free Google Gemini 2.5 Flash model
        self.llm = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash",
            google_api_key=api_key,
            temperature=0.2  # Low temperature ensures strict factual report generation
        )

    def generate_incident_report(self, json_log_path):
        """
        Reads raw JSON log files produced by the LSTM network, orchestrates
        LangChain prompt structures, and outputs a corporate incident report.
        """
        print(f"[AGENT] Reading structural log data from: {json_log_path}")

        with open(json_log_path, 'r') as f:
            raw_telemetry = json.load(f)

        # Build an advanced industrial prompt template for corporate compliance auditing
        report_template = """
        You are a Senior Security AI Analyst at an enterprise monitoring facility.
        Your task is to take a raw JSON automated log payload emitted by an Edge Computer Vision pipeline and transform it into a highly professional, comprehensive corporate Security Incident Report.

        RAW TELEMETRY TELEMETRY PACK:
        {json_payload}

        Please structure your report using the exact following standard operational blocks:
        1. EXECUTIVE SUMMARY: Short clean statement of what occurred.
        2. TECHNICAL DETAILS: Model used, camera ID, timestamp, and mathematical confidence metrics.
        3. LIABILITY AND EVIDENCE ASSESSMENT: Mention the explicit S3 bucket location where evidence data assets are locked.
        4. RECOMMENDED ACTION PLAN: Actionable next steps for physical guards on-site to handle this threat.

        Write your report with a strictly formal, authoritative corporate security tone.
        """

        prompt = PromptTemplate(
            template=report_template,
            input_variables=["json_payload"]
        )

        # Standard LangChain Runnable Sequence execution syntax pipeline
        chain = prompt | self.llm

        print("[AGENT] Sending cloud data telemetry to LLM orchestration nodes...")
        # Format telemetry content seamlessly into string matrix
        formatted_payload = json.dumps(raw_telemetry, indent=4)
        response = chain.invoke({"json_payload": formatted_payload})

        return response.content


if __name__ == "__main__":
    # Automatic sweep to grab the latest JSON log file generated inside the data folder
    json_logs = glob.glob("data/incident_*.json")

    if not json_logs:
        print("[ERROR] No automated JSON incident logs found inside 'data/' folder.")
        print("[HELP] Please run python3 test_threat.py to generate incident telemetries first.")
    else:
        # Pick the newest telemetry profile file
        latest_log = max(json_logs, key=os.path.getctime)

        agent = SecurityIncidentAgent()
        report = agent.generate_incident_report(latest_log)

        print("\n==================================================================")
        print("📁 DISPATCHING ENTERPRISE SECURITY INCIDENT REPORT GENERATED BY LLM:")
        print("==================================================================")
        print(report)
        print("==================================================================\n")